# Site settings
title: Family Recipes
email: training@github.com
description:  A place for all your recipe needs!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: githubtraining
github_username:  githubschool

# Build settings
markdown: kramdown
